[package]
name = "fslite-conformance"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
fslite-core = { path = "../fslite-core", version = "0.1.0" }
futures.workspace = true
